from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from .model_config import OUTPUT_FILES, README_FILE, TARGET_LABEL


def read_csv(path: Path) -> pd.DataFrame:
    if path.exists() and path.stat().st_size > 0:
        try:
            return pd.read_csv(path)
        except Exception:
            return pd.DataFrame()
    return pd.DataFrame()


def md_table(df: pd.DataFrame, max_rows: int = 20, cols: list[str] | None = None) -> str:
    if df.empty:
        return "_No data available yet._"
    x = df.copy()
    if cols:
        x = x[[c for c in cols if c in x.columns]]
    x = x.head(max_rows)
    for c in x.columns:
        if pd.api.types.is_float_dtype(x[c]):
            x[c] = x[c].map(lambda v: "" if pd.isna(v) else f"{v:.4f}")
    return x.to_markdown(index=False)


def main():
    main_result = read_csv(OUTPUT_FILES["main_result"])
    latest = read_csv(OUTPUT_FILES["latest_live"])
    baseline = read_csv(OUTPUT_FILES["strategy_baseline"])
    ablation = read_csv(OUTPUT_FILES["ablation"])
    five = read_csv(OUTPUT_FILES["five_seed"])
    rounds = read_csv(OUTPUT_FILES["rounds_100"])
    rounds_freq = read_csv(OUTPUT_FILES["rounds_frequency"])
    imp = read_csv(OUTPUT_FILES["feature_importance"])
    monthly = read_csv(OUTPUT_FILES["monthly_top"])

    metrics = {}
    if OUTPUT_FILES["metrics_json"].exists():
        try:
            metrics = json.loads(OUTPUT_FILES["metrics_json"].read_text(encoding="utf-8"))
        except Exception:
            metrics = {}

    text = f"""# ETF Tail Boom Prediction Model

This repository trains a right-tail stock-event detector using the panel generated by `panel_label_construct`.
The core target is `{TARGET_LABEL}`: a stock whose future 1–3 month max return is both in the monthly top 10% and at least +30%.

## Run

Put the full panel at:

```bash
data/clean_monthly_panel.csv
```

Then run:

```bash
pip install -r requirements.txt
python run_all.py
```

For a faster smoke test:

```bash
python -m src.train --rounds 5 --skip-ablation
python -m src.update_readme
```

## Leakage rule

The following columns must never be used as model inputs: `future_return_*`, `future_max_return_1_3m`, `future_max_return_1_3m_pct_rank`, monthly thresholds, and every `label_*` column.
The training code automatically excludes them and only keeps numeric feature columns.

## Reference-downweighted main model result

The main model is an XGBoost classifier with reference-downweighted sample weights. Easy/reference negatives are downweighted so they do not dominate the right-tail learning objective; stronger boom labels receive extra weight.

{md_table(main_result, max_rows=5)}

## Latest live boom candidates

Latest month candidates are ranked by an ensemble of the main model, five-seed average score, and 100-round average score when available.

{md_table(latest, max_rows=30, cols=['rank','month','ticker','ensemble_score','main_score','five_seed_avg_score','five_seed_score_std','rounds_100_avg_score','rounds_100_score_std','mom_6m','mom_3m','rel_mom_6m_vs_qqq','liquid_vol_score','avg_dollar_volume_3m'])}

## Strategy and baseline comparison

This compares the model's monthly Top-K selections against simple baselines such as six-month momentum, three-month momentum, relative momentum versus QQQ, and liquidity/volatility score.

{md_table(baseline, max_rows=20, cols=['strategy','split','pr_auc','top3_avg_future_max_return_1_3m','precision_at_top3','top3_hit30_rate','top3_hit50_rate','monthly_any_top3_hit50_rate','top5_avg_future_max_return_1_3m','precision_at_top5'])}

## Ablation ranked summary

Each row drops one feature group and retrains the model. Negative `delta_top3_future_max_vs_main` means the removed group was useful for Top-3 tail capture.

{md_table(ablation, max_rows=30, cols=['ablation','dropped_features','kept_features','top3_avg_future_max_return_1_3m','precision_at_top3','top3_hit30_rate','top3_hit50_rate','monthly_any_top3_hit50_rate','delta_top3_future_max_vs_main'])}

## 100-rounds report

The 100-round report repeatedly trains randomized reference-downweighted XGB models using different seeds, month bootstraps, and light feature subsampling. It measures whether the signal survives perturbation rather than depending on one lucky seed.

{md_table(rounds, max_rows=20, cols=['round','train_months','feature_count','pr_auc','top3_avg_future_max_return_1_3m','precision_at_top3','top3_hit30_rate','top3_hit50_rate','monthly_any_top3_hit50_rate'])}

### 100-round latest candidate frequency

Tickers appearing frequently in the latest top-10 across randomized rounds are more stable live candidates.

{md_table(rounds_freq, max_rows=30)}

## Five-seed training stability

This retrains the same main model with five seeds and checks whether Top-K performance is stable.

{md_table(five, max_rows=10, cols=['seed','pr_auc','top3_avg_future_max_return_1_3m','precision_at_top3','top3_hit30_rate','top3_hit50_rate','monthly_any_top3_hit50_rate','top5_avg_future_max_return_1_3m','precision_at_top5'])}

## Top feature importance

{md_table(imp, max_rows=40)}

## Recent monthly Top-10 model picks

{md_table(monthly.sort_values(['month','rank'], ascending=[False, True]) if not monthly.empty else monthly, max_rows=50, cols=['month','rank','ticker','main_score','future_return_1m','future_return_2m','future_return_3m','future_max_return_1_3m','label_boom30_top10_1_3m','label_boom50_top5_1_3m','label_mega100_1_3m'])}

## Output files

```text
outputs/reference_downweighted_main_model_result.csv
outputs/latest_live_boom_candidates.csv
outputs/strategy_baseline_comparison.csv
outputs/ablation_ranked_summary.csv
outputs/rounds_100_report.csv
outputs/rounds_100_latest_candidate_frequency.csv
outputs/five_seed_training_stability.csv
outputs/feature_importance.csv
outputs/monthly_top_predictions.csv
outputs/model_metrics.json
models/xgb_tail_event_classifier.json
models/selected_features.txt
```

## Notes

- The model is a stock-ranking tool, not a guarantee of future return.
- The main decision output should be monthly Top-3 / Top-5 candidates, not raw probability calibration.
- The panel file is normally too large to commit. Keep it as a GitHub Actions artifact or local file; commit only summaries and model artifacts.
"""
    README_FILE.write_text(text, encoding="utf-8")
    print(f"Updated {README_FILE}")


if __name__ == "__main__":
    main()
